/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ComparisonRecord {
  'id' : string,
  'productIds' : Array<string>,
  'timestamp' : bigint,
}
export type Platform = { 'Amazon' : null } |
  { 'eBay' : null } |
  { 'Other' : string } |
  { 'Flipkart' : null };
export interface PlatformPrice {
  'inStock' : boolean,
  'originalPrice' : number,
  'platform' : Platform,
  'discount' : number,
  'price' : number,
  'buyNowUrl' : string,
}
export interface Product {
  'id' : string,
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'averageRating' : number,
  'imageUrl' : string,
  'platforms' : Array<PlatformPrice>,
  'category' : string,
  'brand' : string,
  'reviewCount' : bigint,
}
export interface SearchQuery {
  'minRating' : [] | [number],
  'maxPrice' : [] | [number],
  'searchTerm' : [] | [string],
  'category' : [] | [string],
  'brand' : [] | [string],
  'minPrice' : [] | [number],
}
export interface UserProfile {
  'userId' : Principal,
  'email' : string,
  'wishlist' : Array<string>,
  'comparisonHistory' : Array<ComparisonRecord>,
}
export type WishlistAction = { 'Add' : null } |
  { 'Remove' : null };
export interface _SERVICE {
  'addToComparisonHistory' : ActorMethod<[Array<string>], undefined>,
  'addToWishlist' : ActorMethod<[string], boolean>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getComparisonHistory' : ActorMethod<[], Array<ComparisonRecord>>,
  'getFavorites' : ActorMethod<[], Array<string>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<string>>,
  'removeFromWishlist' : ActorMethod<[string], boolean>,
  'searchProducts' : ActorMethod<[SearchQuery], Array<Product>>,
  'toggleFavorite' : ActorMethod<[string, WishlistAction], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];