/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Platform = IDL.Variant({
  'Amazon' : IDL.Null,
  'eBay' : IDL.Null,
  'Other' : IDL.Text,
  'Flipkart' : IDL.Null,
});
export const PlatformPrice = IDL.Record({
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Float64,
  'platform' : Platform,
  'discount' : IDL.Float64,
  'price' : IDL.Float64,
  'buyNowUrl' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'averageRating' : IDL.Float64,
  'imageUrl' : IDL.Text,
  'platforms' : IDL.Vec(PlatformPrice),
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'reviewCount' : IDL.Nat,
});
export const ComparisonRecord = IDL.Record({
  'id' : IDL.Text,
  'productIds' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Principal,
  'email' : IDL.Text,
  'wishlist' : IDL.Vec(IDL.Text),
  'comparisonHistory' : IDL.Vec(ComparisonRecord),
});
export const SearchQuery = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'brand' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Float64),
});
export const WishlistAction = IDL.Variant({
  'Add' : IDL.Null,
  'Remove' : IDL.Null,
});

export const idlService = IDL.Service({
  'addToComparisonHistory' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'addToWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getComparisonHistory' : IDL.Func([], [IDL.Vec(ComparisonRecord)], []),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'searchProducts' : IDL.Func([SearchQuery], [IDL.Vec(Product)], ['query']),
  'toggleFavorite' : IDL.Func([IDL.Text, WishlistAction], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Platform = IDL.Variant({
    'Amazon' : IDL.Null,
    'eBay' : IDL.Null,
    'Other' : IDL.Text,
    'Flipkart' : IDL.Null,
  });
  const PlatformPrice = IDL.Record({
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Float64,
    'platform' : Platform,
    'discount' : IDL.Float64,
    'price' : IDL.Float64,
    'buyNowUrl' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'averageRating' : IDL.Float64,
    'imageUrl' : IDL.Text,
    'platforms' : IDL.Vec(PlatformPrice),
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'reviewCount' : IDL.Nat,
  });
  const ComparisonRecord = IDL.Record({
    'id' : IDL.Text,
    'productIds' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Principal,
    'email' : IDL.Text,
    'wishlist' : IDL.Vec(IDL.Text),
    'comparisonHistory' : IDL.Vec(ComparisonRecord),
  });
  const SearchQuery = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'brand' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Float64),
  });
  const WishlistAction = IDL.Variant({ 'Add' : IDL.Null, 'Remove' : IDL.Null });
  
  return IDL.Service({
    'addToComparisonHistory' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'addToWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getComparisonHistory' : IDL.Func([], [IDL.Vec(ComparisonRecord)], []),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'searchProducts' : IDL.Func([SearchQuery], [IDL.Vec(Product)], ['query']),
    'toggleFavorite' : IDL.Func([IDL.Text, WishlistAction], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };