/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchQuery {
    minRating?: number;
    maxPrice?: number;
    searchTerm?: string;
    category?: string;
    brand?: string;
    minPrice?: number;
}
export interface PlatformPrice {
    inStock: boolean;
    originalPrice: number;
    platform: Platform;
    discount: number;
    price: number;
    buyNowUrl: string;
}
export type Platform = {
    __kind__: "Amazon";
    Amazon: null;
} | {
    __kind__: "eBay";
    eBay: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Flipkart";
    Flipkart: null;
};
export interface ComparisonRecord {
    id: string;
    productIds: Array<string>;
    timestamp: bigint;
}
export interface Product {
    id: string;
    title: string;
    tags: Array<string>;
    description: string;
    averageRating: number;
    imageUrl: string;
    platforms: Array<PlatformPrice>;
    category: string;
    brand: string;
    reviewCount: bigint;
}
export interface UserProfile {
    userId: Principal;
    email: string;
    wishlist: Array<string>;
    comparisonHistory: Array<ComparisonRecord>;
}
export enum WishlistAction {
    Add = "Add",
    Remove = "Remove"
}
export interface backendInterface {
    addToComparisonHistory(productIds: Array<string>): Promise<void>;
    addToWishlist(productId: string): Promise<boolean>;
    getAllProducts(): Promise<Array<Product>>;
    getComparisonHistory(): Promise<Array<ComparisonRecord>>;
    getFavorites(): Promise<Array<string>>;
    getProductById(id: string): Promise<Product | null>;
    getUserProfile(): Promise<UserProfile | null>;
    getWishlist(): Promise<Array<string>>;
    removeFromWishlist(productId: string): Promise<boolean>;
    searchProducts(q: SearchQuery): Promise<Array<Product>>;
    toggleFavorite(productId: string, action: WishlistAction): Promise<boolean>;
}
import type { Platform as _Platform, PlatformPrice as _PlatformPrice, Product as _Product, SearchQuery as _SearchQuery, UserProfile as _UserProfile, WishlistAction as _WishlistAction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToComparisonHistory(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToComparisonHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToComparisonHistory(arg0);
            return result;
        }
    }
    async addToWishlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComparisonHistory(): Promise<Array<ComparisonRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComparisonHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComparisonHistory();
            return result;
        }
    }
    async getFavorites(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getProductById(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async removeFromWishlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async searchProducts(arg0: SearchQuery): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(to_candid_SearchQuery_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(to_candid_SearchQuery_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleFavorite(arg0: string, arg1: WishlistAction): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0, to_candid_WishlistAction_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0, to_candid_WishlistAction_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PlatformPrice_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformPrice): PlatformPrice {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    tags: Array<string>;
    description: string;
    averageRating: number;
    imageUrl: string;
    platforms: Array<_PlatformPrice>;
    category: string;
    brand: string;
    reviewCount: bigint;
}): {
    id: string;
    title: string;
    tags: Array<string>;
    description: string;
    averageRating: number;
    imageUrl: string;
    platforms: Array<PlatformPrice>;
    category: string;
    brand: string;
    reviewCount: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        tags: value.tags,
        description: value.description,
        averageRating: value.averageRating,
        imageUrl: value.imageUrl,
        platforms: from_candid_vec_n4(_uploadFile, _downloadFile, value.platforms),
        category: value.category,
        brand: value.brand,
        reviewCount: value.reviewCount
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: boolean;
    originalPrice: number;
    platform: _Platform;
    discount: number;
    price: number;
    buyNowUrl: string;
}): {
    inStock: boolean;
    originalPrice: number;
    platform: Platform;
    discount: number;
    price: number;
    buyNowUrl: string;
} {
    return {
        inStock: value.inStock,
        originalPrice: value.originalPrice,
        platform: from_candid_Platform_n7(_uploadFile, _downloadFile, value.platform),
        discount: value.discount,
        price: value.price,
        buyNowUrl: value.buyNowUrl
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Amazon: null;
} | {
    eBay: null;
} | {
    Other: string;
} | {
    Flipkart: null;
}): {
    __kind__: "Amazon";
    Amazon: null;
} | {
    __kind__: "eBay";
    eBay: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Flipkart";
    Flipkart: null;
} {
    return "Amazon" in value ? {
        __kind__: "Amazon",
        Amazon: value.Amazon
    } : "eBay" in value ? {
        __kind__: "eBay",
        eBay: value.eBay
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "Flipkart" in value ? {
        __kind__: "Flipkart",
        Flipkart: value.Flipkart
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlatformPrice>): Array<PlatformPrice> {
    return value.map((x)=>from_candid_PlatformPrice_n5(_uploadFile, _downloadFile, x));
}
function to_candid_SearchQuery_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchQuery): _SearchQuery {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_WishlistAction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WishlistAction): _WishlistAction {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minRating?: number;
    maxPrice?: number;
    searchTerm?: string;
    category?: string;
    brand?: string;
    minPrice?: number;
}): {
    minRating: [] | [number];
    maxPrice: [] | [number];
    searchTerm: [] | [string];
    category: [] | [string];
    brand: [] | [string];
    minPrice: [] | [number];
} {
    return {
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        brand: value.brand ? candid_some(value.brand) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WishlistAction): {
    Add: null;
} | {
    Remove: null;
} {
    return value == WishlistAction.Add ? {
        Add: null
    } : value == WishlistAction.Remove ? {
        Remove: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
